# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin1Code',
            fields=[
                ('geonameid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Admin2Code',
            fields=[
                ('geonameid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('admin1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins2', to='places.Admin1Code')),
            ],
        ),
        migrations.CreateModel(
            name='AlternateName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_preferred_name', models.BooleanField(default=False)),
                ('is_short_name', models.BooleanField(default=False)),
                ('is_asciified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('geonameid', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('geonameid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('feature_class', models.CharField(max_length=1)),
                ('feature_code', models.CharField(max_length=10)),
                ('population', models.BigIntegerField(null=True)),
                ('admin1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='places.Admin1Code')),
                ('admin2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='places.Admin2Code')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='places.Country')),
            ],
        ),
        migrations.AddField(
            model_name='alternatename',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatenames', to='places.Locality'),
        ),
        migrations.AddField(
            model_name='admin2code',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins2', to='places.Country'),
        ),
        migrations.AddField(
            model_name='admin1code',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins1', to='places.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='admin2code',
            unique_together=set([('country', 'admin1', 'name')]),
        ),
    ]
