# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX places_country_name_idx ON places_country (name COLLATE NOCASE);",
            "DROP INDEX places_country_name_idx;"
        ),

        migrations.RunSQL(
            "CREATE INDEX places_admin1code_name_idx ON places_admin1code (name COLLATE NOCASE);",
            "DROP INDEX places_admin1code_name_idx;"
        ),

        migrations.RunSQL(
            "CREATE INDEX places_admin2code_name_idx ON places_admin2code (name COLLATE NOCASE);",
            "DROP INDEX places_admin2code_name_idx;"
        ),

        migrations.RunSQL(
            "CREATE INDEX places_locality_name_idx ON places_locality (name COLLATE NOCASE);",
            "DROP INDEX places_locality_name_idx;"
        ),

        migrations.RunSQL(
            "CREATE INDEX places_alternatename_name_idx ON places_alternatename (name COLLATE NOCASE);",
            "DROP INDEX places_alternatename_name_idx;"
        ),
    ]
